In [1]:
import numpy as np
import pandas as pn


In [2]:
l=['1','2','3']
print(np.array(l))

['1' '2' '3']


In [3]:
a=np.ones(5)

In [4]:
print(a)

[1. 1. 1. 1. 1.]


In [5]:
b=np.zeros(10)

In [6]:
b=np.zeros(10)

In [7]:
print(b)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [8]:
b.dtype

dtype('float64')

In [9]:
c=np.ones((3,3),int)

In [10]:
print(c)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [11]:
print()

In [12]:
d=np.ones((3,3,2),int)

In [13]:
print(d)

[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]


In [14]:
pn.__version__


'1.0.1'

In [15]:
titanic_df=pn.read_csv('titanic.csv')

In [16]:
print(titanic_df)

     Pclass                                            Name     Sex   Age  \
0         2   Weisz, Mrs. Leopold (Mathilde Francoise Pede)  female  29.0   
1         3               Williams, Mr. Howard Hugh "Harry"    male   NaN   
2         2  Morley, Mr. Henry Samuel ("Mr Henry Marshall")    male  39.0   
3         3     Palsson, Mrs. Nils (Alma Cornelia Berglund)  female  29.0   
4         3                          Sutehall, Mr. Henry Jr    male  25.0   
..      ...                                             ...     ...   ...   
663       2                             Ilett, Miss. Bertha  female  17.0   
664       3                        Morrow, Mr. Thomas Rowan    male   NaN   
665       3                                   Bing, Mr. Lee    male  32.0   
666       3                     Strandberg, Miss. Ida Sofia  female  22.0   
667       3                  Murphy, Miss. Katherine "Kate"  female   NaN   

     SibSp  Parch           Ticket     Fare Cabin Embarked  Survived  
0   

In [17]:
titanic_df.head()

Pclass                                            Name     Sex   Age  \
0       2   Weisz, Mrs. Leopold (Mathilde Francoise Pede)  female  29.0   
1       3               Williams, Mr. Howard Hugh "Harry"    male   NaN   
2       2  Morley, Mr. Henry Samuel ("Mr Henry Marshall")    male  39.0   
3       3     Palsson, Mrs. Nils (Alma Cornelia Berglund)  female  29.0   
4       3                          Sutehall, Mr. Henry Jr    male  25.0   

   SibSp  Parch           Ticket    Fare Cabin Embarked  Survived  
0      1      0           228414  26.000   NaN        S         1  
1      0      0         A/5 2466   8.050   NaN        S         0  
2      0      0           250655  26.000   NaN        S         0  
3      0      4           349909  21.075   NaN        S         0  
4      0      0  SOTON/OQ 392076   7.050   NaN        S         0

In [18]:
titanic_df.describe()

Pclass         Age       SibSp       Parch        Fare    Survived
count  668.000000  536.000000  668.000000  668.000000  668.000000  668.000000
mean     2.296407   29.700560    0.528443    0.407186   32.064552    0.402695
std      0.831638   14.240257    1.080327    0.854695   45.320835    0.490808
min      1.000000    0.670000    0.000000    0.000000    0.000000    0.000000
25%      2.000000   21.000000    0.000000    0.000000    7.925000    0.000000
50%      3.000000   29.000000    0.000000    0.000000   14.750000    0.000000
75%      3.000000   38.250000    1.000000    0.000000   31.275000    1.000000
max      3.000000   80.000000    8.000000    6.000000  512.329200    1.000000

In [19]:
titanic_df.head(600)

Pclass                                            Name     Sex   Age  \
0         2   Weisz, Mrs. Leopold (Mathilde Francoise Pede)  female  29.0   
1         3               Williams, Mr. Howard Hugh "Harry"    male   NaN   
2         2  Morley, Mr. Henry Samuel ("Mr Henry Marshall")    male  39.0   
3         3     Palsson, Mrs. Nils (Alma Cornelia Berglund)  female  29.0   
4         3                          Sutehall, Mr. Henry Jr    male  25.0   
..      ...                                             ...     ...   ...   
595       1                             Robbins, Mr. Victor    male   NaN   
596       3                    Theobald, Mr. Thomas Leonard    male  34.0   
597       2                    Lemore, Mrs. (Amelia Milley)  female  34.0   
598       1                        Uruchurtu, Don. Manuel E    male  40.0   
599       3                 Vander Planke, Mr. Leo Edmondus    male  16.0   

     SibSp  Parch           Ticket      Fare Cabin Embarked  Survived  
0        1      0           228414   26.0000   NaN        S         1  
1        0      0         A/5 2466    8.0500   NaN        S         0  
2        0      0           250655   26.0000   NaN        S         0  
3        0      4           349909   21.0750   NaN        S         0  
4        0      0  SOTON/OQ 392076    7.0500   NaN        S         0  
..     ...    ...              ...       ...   ...      ...       ...  
595      0      0         PC 17757  227.5250   NaN        C         0  
596      0      0           363294    8.0500   NaN        S         0  
597      0      0       C.A. 34260   10.5000   F33        S         1  
598      0      0         PC 17601   27.7208   NaN        C         0  
599      2      0           345764   18.0000   NaN        S         0  

[600 rows x 11 columns]

In [20]:
titanic_df

Pclass                                            Name     Sex   Age  \
0         2   Weisz, Mrs. Leopold (Mathilde Francoise Pede)  female  29.0   
1         3               Williams, Mr. Howard Hugh "Harry"    male   NaN   
2         2  Morley, Mr. Henry Samuel ("Mr Henry Marshall")    male  39.0   
3         3     Palsson, Mrs. Nils (Alma Cornelia Berglund)  female  29.0   
4         3                          Sutehall, Mr. Henry Jr    male  25.0   
..      ...                                             ...     ...   ...   
663       2                             Ilett, Miss. Bertha  female  17.0   
664       3                        Morrow, Mr. Thomas Rowan    male   NaN   
665       3                                   Bing, Mr. Lee    male  32.0   
666       3                     Strandberg, Miss. Ida Sofia  female  22.0   
667       3                  Murphy, Miss. Katherine "Kate"  female   NaN   

     SibSp  Parch           Ticket     Fare Cabin Embarked  Survived  
0        1      0           228414  26.0000   NaN        S         1  
1        0      0         A/5 2466   8.0500   NaN        S         0  
2        0      0           250655  26.0000   NaN        S         0  
3        0      4           349909  21.0750   NaN        S         0  
4        0      0  SOTON/OQ 392076   7.0500   NaN        S         0  
..     ...    ...              ...      ...   ...      ...       ...  
663      0      0       SO/C 14885  10.5000   NaN        S         1  
664      0      0           372622   7.7500   NaN        Q         0  
665      0      0             1601  56.4958   NaN        S         1  
666      0      0             7553   9.8375   NaN        S         0  
667      1      0           367230  15.5000   NaN        Q         1  

[668 rows x 11 columns]

In [21]:
iris=pn.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data')

In [22]:
iris=pn.read_csv('iris.data')

In [23]:
iris


5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

In [24]:
iris_df=iris.copy()

In [25]:
iris_df


5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

In [26]:
iris_df.dtypes

5.1            float64
3.5            float64
1.4            float64
0.2            float64
Iris-setosa     object
dtype: object

In [27]:
iris_df.head(3)

5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa

In [28]:
iris_df.columns


Index(['5.1', '3.5', '1.4', '0.2', 'Iris-setosa'], dtype='object')

In [29]:
iris_df.columns=['SepalLength','SepalWidth','PetalLength','PetalWidth','FlowerType']

In [30]:
iris_df.head(3)

SepalLength  SepalWidth  PetalLength  PetalWidth   FlowerType
0          4.9         3.0          1.4         0.2  Iris-setosa
1          4.7         3.2          1.3         0.2  Iris-setosa
2          4.6         3.1          1.5         0.2  Iris-setosa

In [31]:
iris_df.isnull()

SepalLength  SepalWidth  PetalLength  PetalWidth  FlowerType
0          False       False        False       False       False
1          False       False        False       False       False
2          False       False        False       False       False
3          False       False        False       False       False
4          False       False        False       False       False
..           ...         ...          ...         ...         ...
144        False       False        False       False       False
145        False       False        False       False       False
146        False       False        False       False       False
147        False       False        False       False       False
148        False       False        False       False       False

[149 rows x 5 columns]

In [32]:
iris_df.isnull().sum()

SepalLength    0
SepalWidth     0
PetalLength    0
PetalWidth     0
FlowerType     0
dtype: int64

In [33]:
iris_df.iloc[1:5,1:4]

SepalWidth  PetalLength  PetalWidth
1         3.2          1.3         0.2
2         3.1          1.5         0.2
3         3.6          1.4         0.2
4         3.9          1.7         0.4

In [34]:
iris_df.iloc[21:25,1:4]

SepalWidth  PetalLength  PetalWidth
21         3.6          1.0         0.2
22         3.3          1.7         0.5
23         3.4          1.9         0.2
24         3.0          1.6         0.2

In [35]:
iris_df.iloc[21:25,1:8]

SepalWidth  PetalLength  PetalWidth   FlowerType
21         3.6          1.0         0.2  Iris-setosa
22         3.3          1.7         0.5  Iris-setosa
23         3.4          1.9         0.2  Iris-setosa
24         3.0          1.6         0.2  Iris-setosa

In [36]:
titanic_df

Pclass                                            Name     Sex   Age  \
0         2   Weisz, Mrs. Leopold (Mathilde Francoise Pede)  female  29.0   
1         3               Williams, Mr. Howard Hugh "Harry"    male   NaN   
2         2  Morley, Mr. Henry Samuel ("Mr Henry Marshall")    male  39.0   
3         3     Palsson, Mrs. Nils (Alma Cornelia Berglund)  female  29.0   
4         3                          Sutehall, Mr. Henry Jr    male  25.0   
..      ...                                             ...     ...   ...   
663       2                             Ilett, Miss. Bertha  female  17.0   
664       3                        Morrow, Mr. Thomas Rowan    male   NaN   
665       3                                   Bing, Mr. Lee    male  32.0   
666       3                     Strandberg, Miss. Ida Sofia  female  22.0   
667       3                  Murphy, Miss. Katherine "Kate"  female   NaN   

     SibSp  Parch           Ticket     Fare Cabin Embarked  Survived  
0        1      0           228414  26.0000   NaN        S         1  
1        0      0         A/5 2466   8.0500   NaN        S         0  
2        0      0           250655  26.0000   NaN        S         0  
3        0      4           349909  21.0750   NaN        S         0  
4        0      0  SOTON/OQ 392076   7.0500   NaN        S         0  
..     ...    ...              ...      ...   ...      ...       ...  
663      0      0       SO/C 14885  10.5000   NaN        S         1  
664      0      0           372622   7.7500   NaN        Q         0  
665      0      0             1601  56.4958   NaN        S         1  
666      0      0             7553   9.8375   NaN        S         0  
667      1      0           367230  15.5000   NaN        Q         1  

[668 rows x 11 columns]

In [37]:
titanic_df.iloc[56:65,0:7]

Pclass                                          Name     Sex   Age  SibSp  \
56       3                             Cor, Mr. Liudevit    male  19.0      0   
57       3                            Garfirth, Mr. John    male   NaN      0   
58       3              Olsen, Mr. Karl Siegwart Andreas    male  42.0      0   
59       1             Kenyon, Mrs. Frederick R (Marion)  female   NaN      1   
60       2                    Downton, Mr. William James    male  54.0      0   
61       1               Homer, Mr. Harry ("Mr E Haven")    male  35.0      0   
62       1                Porter, Mr. Walter Chamberlain    male  47.0      0   
63       1  Harris, Mrs. Henry Birkhardt (Irene Wallach)  female  35.0      1   
64       1                  Barber, Miss. Ellen "Nellie"  female  26.0      0   

    Parch  Ticket  
56      0  349231  
57      0  358585  
58      1    4579  
59      0   17464  
60      0   28403  
61      0  111426  
62      0  110465  
63      0   36973  
64      0   19877

In [38]:
cl=iris_df[iris_df.FlowerType=='Iris-setosa']
print(cl.describe())
print()
print()
 
print(cl.SepalLength>5.03)

       SepalLength  SepalWidth  PetalLength  PetalWidth
count    49.000000   49.000000    49.000000   49.000000
mean      5.004082    3.416327     1.465306    0.244898
std       0.355879    0.384787     0.175061    0.108130
min       4.300000    2.300000     1.000000    0.100000
25%       4.800000    3.100000     1.400000    0.200000
50%       5.000000    3.400000     1.500000    0.200000
75%       5.200000    3.700000     1.600000    0.300000
max       5.800000    4.400000     1.900000    0.600000


0     False
1     False
2     False
3     False
4      True
5     False
6     False
7     False
8     False
9      True
10    False
11    False
12    False
13     True
14     True
15     True
16     True
17     True
18     True
19     True
20     True
21    False
22     True
23    False
24    False
25    False
26     True
27     True
28    False
29    False
30     True
31     True
32     True
33    False
34    False
35     True
36    False
37    False
38     True
39    False
40    False
41

In [39]:
titanic_df.iloc[1:5,0:7]

Pclass                                            Name     Sex   Age  \
1       3               Williams, Mr. Howard Hugh "Harry"    male   NaN   
2       2  Morley, Mr. Henry Samuel ("Mr Henry Marshall")    male  39.0   
3       3     Palsson, Mrs. Nils (Alma Cornelia Berglund)  female  29.0   
4       3                          Sutehall, Mr. Henry Jr    male  25.0   

   SibSp  Parch           Ticket  
1      0      0         A/5 2466  
2      0      0           250655  
3      0      4           349909  
4      0      0  SOTON/OQ 392076

In [40]:
titanic_df.iloc[3]

Pclass                                                3
Name        Palsson, Mrs. Nils (Alma Cornelia Berglund)
Sex                                              female
Age                                                  29
SibSp                                                 0
Parch                                                 4
Ticket                                           349909
Fare                                             21.075
Cabin                                               NaN
Embarked                                              S
Survived                                              0
Name: 3, dtype: object

In [41]:
titanic_df.loc[3]

Pclass                                                3
Name        Palsson, Mrs. Nils (Alma Cornelia Berglund)
Sex                                              female
Age                                                  29
SibSp                                                 0
Parch                                                 4
Ticket                                           349909
Fare                                             21.075
Cabin                                               NaN
Embarked                                              S
Survived                                              0
Name: 3, dtype: object

In [42]:
iris_df.loc[150]=['5.4','3.1','6.8','4.9','Iris-setosa']

In [44]:
iris_df.tail()

SepalLength SepalWidth PetalLength PetalWidth      FlowerType
145         6.3        2.5           5        1.9  Iris-virginica
146         6.5          3         5.2          2  Iris-virginica
147         6.2        3.4         5.4        2.3  Iris-virginica
148         5.9          3         5.1        1.8  Iris-virginica
150         5.4        3.1         6.8        4.9     Iris-setosa

In [45]:
iris_df.drop('SepalWidth',axis=1)

SepalLength PetalLength PetalWidth      FlowerType
0           4.9         1.4        0.2     Iris-setosa
1           4.7         1.3        0.2     Iris-setosa
2           4.6         1.5        0.2     Iris-setosa
3             5         1.4        0.2     Iris-setosa
4           5.4         1.7        0.4     Iris-setosa
..          ...         ...        ...             ...
145         6.3           5        1.9  Iris-virginica
146         6.5         5.2          2  Iris-virginica
147         6.2         5.4        2.3  Iris-virginica
148         5.9         5.1        1.8  Iris-virginica
150         5.4         6.8        4.9     Iris-setosa

[150 rows x 4 columns]

In [47]:
iris_df

SepalLength SepalWidth PetalLength PetalWidth      FlowerType
0           4.9          3         1.4        0.2     Iris-setosa
1           4.7        3.2         1.3        0.2     Iris-setosa
2           4.6        3.1         1.5        0.2     Iris-setosa
3             5        3.6         1.4        0.2     Iris-setosa
4           5.4        3.9         1.7        0.4     Iris-setosa
..          ...        ...         ...        ...             ...
145         6.3        2.5           5        1.9  Iris-virginica
146         6.5          3         5.2          2  Iris-virginica
147         6.2        3.4         5.4        2.3  Iris-virginica
148         5.9          3         5.1        1.8  Iris-virginica
150         5.4        3.1         6.8        4.9     Iris-setosa

[150 rows x 5 columns]

In [48]:
cl

SepalLength  SepalWidth  PetalLength  PetalWidth   FlowerType
0           4.9         3.0          1.4         0.2  Iris-setosa
1           4.7         3.2          1.3         0.2  Iris-setosa
2           4.6         3.1          1.5         0.2  Iris-setosa
3           5.0         3.6          1.4         0.2  Iris-setosa
4           5.4         3.9          1.7         0.4  Iris-setosa
5           4.6         3.4          1.4         0.3  Iris-setosa
6           5.0         3.4          1.5         0.2  Iris-setosa
7           4.4         2.9          1.4         0.2  Iris-setosa
8           4.9         3.1          1.5         0.1  Iris-setosa
9           5.4         3.7          1.5         0.2  Iris-setosa
10          4.8         3.4          1.6         0.2  Iris-setosa
11          4.8         3.0          1.4         0.1  Iris-setosa
12          4.3         3.0          1.1         0.1  Iris-setosa
13          5.8         4.0          1.2         0.2  Iris-setosa
14          5.7         4.4          1.5         0.4  Iris-setosa
15          5.4         3.9          1.3         0.4  Iris-setosa
16          5.1         3.5          1.4         0.3  Iris-setosa
17          5.7         3.8          1.7         0.3  Iris-setosa
18          5.1         3.8          1.5         0.3  Iris-setosa
19          5.4         3.4          1.7         0.2  Iris-setosa
20          5.1         3.7          1.5         0.4  Iris-setosa
21          4.6         3.6          1.0         0.2  Iris-setosa
22          5.1         3.3          1.7         0.5  Iris-setosa
23          4.8         3.4          1.9         0.2  Iris-setosa
24          5.0         3.0          1.6         0.2  Iris-setosa
25          5.0         3.4          1.6         0.4  Iris-setosa
26          5.2         3.5          1.5         0.2  Iris-setosa
27          5.2         3.4          1.4         0.2  Iris-setosa
28          4.7         3.2          1.6         0.2  Iris-setosa
29          4.8         3.1          1.6         0.2  Iris-setosa
30          5.4         3.4          1.5         0.4  Iris-setosa
31          5.2         4.1          1.5         0.1  Iris-setosa
32          5.5         4.2          1.4         0.2  Iris-setosa
33          4.9         3.1          1.5         0.1  Iris-setosa
34          5.0         3.2          1.2         0.2  Iris-setosa
35          5.5         3.5          1.3         0.2  Iris-setosa
36          4.9         3.1          1.5         0.1  Iris-setosa
37          4.4         3.0          1.3         0.2  Iris-setosa
38          5.1         3.4          1.5         0.2  Iris-setosa
39          5.0         3.5          1.3         0.3  Iris-setosa
40          4.5         2.3          1.3         0.3  Iris-setosa
41          4.4         3.2          1.3         0.2  Iris-setosa
42          5.0         3.5          1.6         0.6  Iris-setosa
43          5.1         3.8          1.9         0.4  Iris-setosa
44          4.8         3.0          1.4         0.3  Iris-setosa
45          5.1         3.8          1.6         0.2  Iris-setosa
46          4.6         3.2          1.4         0.2  Iris-setosa
47          5.3         3.7          1.5         0.2  Iris-setosa
48          5.0         3.3          1.4         0.2  Iris-setosa

In [51]:
cl.columns=['sl','sw','pl','pw','Type']
cl

sl   sw   pl   pw         Type
0   4.9  3.0  1.4  0.2  Iris-setosa
1   4.7  3.2  1.3  0.2  Iris-setosa
2   4.6  3.1  1.5  0.2  Iris-setosa
3   5.0  3.6  1.4  0.2  Iris-setosa
4   5.4  3.9  1.7  0.4  Iris-setosa
5   4.6  3.4  1.4  0.3  Iris-setosa
6   5.0  3.4  1.5  0.2  Iris-setosa
7   4.4  2.9  1.4  0.2  Iris-setosa
8   4.9  3.1  1.5  0.1  Iris-setosa
9   5.4  3.7  1.5  0.2  Iris-setosa
10  4.8  3.4  1.6  0.2  Iris-setosa
11  4.8  3.0  1.4  0.1  Iris-setosa
12  4.3  3.0  1.1  0.1  Iris-setosa
13  5.8  4.0  1.2  0.2  Iris-setosa
14  5.7  4.4  1.5  0.4  Iris-setosa
15  5.4  3.9  1.3  0.4  Iris-setosa
16  5.1  3.5  1.4  0.3  Iris-setosa
17  5.7  3.8  1.7  0.3  Iris-setosa
18  5.1  3.8  1.5  0.3  Iris-setosa
19  5.4  3.4  1.7  0.2  Iris-setosa
20  5.1  3.7  1.5  0.4  Iris-setosa
21  4.6  3.6  1.0  0.2  Iris-setosa
22  5.1  3.3  1.7  0.5  Iris-setosa
23  4.8  3.4  1.9  0.2  Iris-setosa
24  5.0  3.0  1.6  0.2  Iris-setosa
25  5.0  3.4  1.6  0.4  Iris-setosa
26  5.2  3.5  1.5  0.2  Iris-setosa
27  5.2  3.4  1.4  0.2  Iris-setosa
28  4.7  3.2  1.6  0.2  Iris-setosa
29  4.8  3.1  1.6  0.2  Iris-setosa
30  5.4  3.4  1.5  0.4  Iris-setosa
31  5.2  4.1  1.5  0.1  Iris-setosa
32  5.5  4.2  1.4  0.2  Iris-setosa
33  4.9  3.1  1.5  0.1  Iris-setosa
34  5.0  3.2  1.2  0.2  Iris-setosa
35  5.5  3.5  1.3  0.2  Iris-setosa
36  4.9  3.1  1.5  0.1  Iris-setosa
37  4.4  3.0  1.3  0.2  Iris-setosa
38  5.1  3.4  1.5  0.2  Iris-setosa
39  5.0  3.5  1.3  0.3  Iris-setosa
40  4.5  2.3  1.3  0.3  Iris-setosa
41  4.4  3.2  1.3  0.2  Iris-setosa
42  5.0  3.5  1.6  0.6  Iris-setosa
43  5.1  3.8  1.9  0.4  Iris-setosa
44  4.8  3.0  1.4  0.3  Iris-setosa
45  5.1  3.8  1.6  0.2  Iris-setosa
46  4.6  3.2  1.4  0.2  Iris-setosa
47  5.3  3.7  1.5  0.2  Iris-setosa
48  5.0  3.3  1.4  0.2  Iris-setosa

In [57]:
cl=iris_df.copy()
cl
cl.columns=['sl','sw','pl','pw','FType']
cl

sl   sw   pl   pw           FType
0    4.9    3  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3      5  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.3  2.5    5  1.9  Iris-virginica
146  6.5    3  5.2    2  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9    3  5.1  1.8  Iris-virginica
150  5.4  3.1  6.8  4.9     Iris-setosa

[150 rows x 5 columns]

In [59]:
cl.describe()

sl     sw     pl     pw           FType
count   150.0  150.0  150.0  150.0             150
unique   36.0   24.0   44.0   23.0               3
top       5.0    3.0    1.5    0.2  Iris-virginica
freq     10.0   26.0   14.0   27.0              50

In [63]:
cl.dtypes

sl       object
sw       object
pl       object
pw       object
FType    object
dtype: object

In [81]:
cl['sl']=cl['sl'].astype(float)
cl['sw']=cl['sw'].astype(float)
cl['pl']=cl['pl'].astype(float)
cl['pw']=cl['pw'].astype(float)


In [82]:
cl.dtypes

sl       float64
sw       float64
pl       float64
pw       float64
FType     object
dtype: object

In [83]:
cl['diff_pl_pw']=cl['pl']-cl['pw']

In [84]:
cl.tail()

sl   sw   pl   pw           FType  diff_pl_pw
145  6.3  2.5  5.0  1.9  Iris-virginica         3.1
146  6.5  3.0  5.2  2.0  Iris-virginica         3.2
147  6.2  3.4  5.4  2.3  Iris-virginica         3.1
148  5.9  3.0  5.1  1.8  Iris-virginica         3.3
150  5.4  3.1  6.8  4.9     Iris-setosa         1.9